name: "CI with One Image"

on:
  workflow_call:
    inputs:
      image-name:
        description: "name of the to be used image"
        required: true
        type: string
      image-tag:
        description: "tag of the to be used image"
        required: true
        type: string

jobs:
  CI-Run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: redhat-actions/buildah-build@v2
      name: "build image"
      with:
        image: libnexpod-test-${{ inputs.image-name }}
        tags: ${{ inputs.image-tag }}
        containerfiles: images/${{ inputs.image-name }}/Containerfile
    - uses: mlugg/setup-zig@v1
      with:
        version: 0.13.0
    - name: "Debug"
      run: |
        zig build
        zig build test
    - name: "Release"
      run: |
        zig build --release
        zig build test --release
